# Generated by Django 3.0.4 on 2021-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncoverBooks', '0011_product_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
