# Generated by Django 3.0.4 on 2021-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncoverBooks', '0014_auto_20210706_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Index',
            field=models.IntegerField(default=0),
        ),
    ]
